server:
  tomcat:
    remote_ip_header: x-forwarded-for
security:
  ignored: /favicon.ico, /
  basic:
    enabled: false
  user:
    password: password
idServiceUrl: ${vcap.services.sso.credentials.auth_domain:localhost:8080/uaa}
spring.oauth2:
    client:
      accessTokenUri: ${idServiceUrl}/oauth/token
      userAuthorizationUri: ${idServiceUrl}/oauth/authorize
      clientId: ${vcap.services.sso.credentials.client_id:acme}
      clientSecret: ${vcap.services.sso.credentials.client_secret:acmesecret}
    resource:
#      jwt.keyUri: ${idServiceUrl}/token_key
      userInfoUri: ${idServiceUrl}/userinfo